### ISSUE TITLE
Push payload to client

### ISSUE THREAD

**Issue by tgrk** [mmzeeman/elli_websocket#4]
I am trying to implement handler based on examples but I am missing way to push payload from server to a client.

**Comment by evanmcc** [comment]
You should be able to do `self() ! payload` then handle that message and push the payload in the `websocket_info` callback, no?

**Comment by evanmcc** [comment]
I just now read the date here.

**Comment by tgrk** [comment]
Thanks I completely "ignored" standard Erlang way to do that.
